// AUTO-GENERATED by scripts/generate_schedule.py - do not hand-edit
const PUZZLE_SCHEDULE = {
  "2026-07-27": {
    "easy": {
      "start": "sea",
      "final": "stale"
    },
    "medium": {
      "start": "an",
      "final": "nation"
    },
    "hard": {
      "start": "grid",
      "final": "badgering"
    }
  },
  "2026-07-28": {
    "easy": {
      "start": "ice",
      "final": "since"
    },
    "medium": {
      "start": "an",
      "final": "dancers"
    },
    "hard": {
      "start": "nut",
      "final": "caution"
    }
  },
  "2026-07-29": {
    "easy": {
      "start": "ar",
      "final": "racer"
    },
    "medium": {
      "start": "by",
      "final": "bygone"
    },
    "hard": {
      "start": "go",
      "final": "gorgeous"
    }
  },
  "2026-07-30": {
    "easy": {
      "start": "in",
      "final": "diner"
    },
    "medium": {
      "start": "act",
      "final": "clarinet"
    },
    "hard": {
      "start": "drag",
      "final": "generated"
    }
  },
  "2026-07-31": {
    "easy": {
      "start": "it",
      "final": "think"
    },
    "medium": {
      "start": "in",
      "final": "sentient"
    },
    "hard": {
      "start": "entice",
      "final": "respecting"
    }
  },
  "2026-08-01": {
    "easy": {
      "start": "oh",
      "final": "mouth"
    },
    "medium": {
      "start": "elf",
      "final": "fealty"
    },
    "hard": {
      "start": "dame",
      "final": "exclaimed"
    }
  },
  "2026-08-02": {
    "easy": {
      "start": "sip",
      "final": "spire"
    },
    "medium": {
      "start": "deform",
      "final": "performed"
    },
    "hard": {
      "start": "ace",
      "final": "correlated"
    }
  },
  "2026-08-03": {
    "easy": {
      "start": "us",
      "final": "bushy"
    },
    "medium": {
      "start": "me",
      "final": "premier"
    },
    "hard": {
      "start": "is",
      "final": "despotic"
    }
  },
  "2026-08-04": {
    "easy": {
      "start": "as",
      "final": "scared"
    },
    "medium": {
      "start": "ear",
      "final": "dewatering"
    },
    "hard": {
      "start": "trounce",
      "final": "countryside"
    }
  },
  "2026-08-05": {
    "easy": {
      "start": "at",
      "final": "crater"
    },
    "medium": {
      "start": "pi",
      "final": "decipher"
    },
    "hard": {
      "start": "sine",
      "final": "burnished"
    }
  },
  "2026-08-06": {
    "easy": {
      "start": "be",
      "final": "edible"
    },
    "medium": {
      "start": "leer",
      "final": "remodeled"
    },
    "hard": {
      "start": "creative",
      "final": "eviscerated"
    }
  },
  "2026-08-07": {
    "easy": {
      "start": "can",
      "final": "arcane"
    },
    "medium": {
      "start": "a",
      "final": "assertion"
    },
    "hard": {
      "start": "nag",
      "final": "integrating"
    }
  },
  "2026-08-08": {
    "easy": {
      "start": "are",
      "final": "dermal"
    },
    "medium": {
      "start": "sis",
      "final": "presides"
    },
    "hard": {
      "start": "ed",
      "final": "repulsed"
    }
  },
  "2026-08-09": {
    "easy": {
      "start": "set",
      "final": "started"
    },
    "medium": {
      "start": "at",
      "final": "tarmac"
    },
    "hard": {
      "start": "tuna",
      "final": "debutante"
    }
  },
  "2026-08-10": {
    "easy": {
      "start": "pal",
      "final": "player"
    },
    "medium": {
      "start": "live",
      "final": "believer"
    },
    "hard": {
      "start": "incite",
      "final": "iridescent"
    }
  },
  "2026-08-11": {
    "easy": {
      "start": "by",
      "final": "blurry"
    },
    "medium": {
      "start": "pi",
      "final": "despoiled"
    },
    "hard": {
      "start": "tab",
      "final": "obstinate"
    }
  },
  "2026-08-12": {
    "easy": {
      "start": "say",
      "final": "sprayed"
    },
    "medium": {
      "start": "an",
      "final": "traipsing"
    },
    "hard": {
      "start": "in",
      "final": "angelic"
    }
  },
  "2026-08-13": {
    "easy": {
      "start": "or",
      "final": "devour"
    },
    "medium": {
      "start": "ad",
      "final": "demeanor"
    },
    "hard": {
      "start": "me",
      "final": "medication"
    }
  },
  "2026-08-14": {
    "easy": {
      "start": "oh",
      "final": "howlers"
    },
    "medium": {
      "start": "es",
      "final": "masteries"
    },
    "hard": {
      "start": "pics",
      "final": "processing"
    }
  },
  "2026-08-15": {
    "easy": {
      "start": "hem",
      "final": "helmet"
    },
    "medium": {
      "start": "ma",
      "final": "rampant"
    },
    "hard": {
      "start": "er",
      "final": "pointier"
    }
  },
  "2026-08-16": {
    "easy": {
      "start": "be",
      "final": "birdies"
    },
    "medium": {
      "start": "asp",
      "final": "pulsated"
    },
    "hard": {
      "start": "is",
      "final": "plastering"
    }
  },
  "2026-08-17": {
    "easy": {
      "start": "is",
      "final": "flimsy"
    },
    "medium": {
      "start": "en",
      "final": "bargeman"
    },
    "hard": {
      "start": "to",
      "final": "rotation"
    }
  },
  "2026-08-18": {
    "easy": {
      "start": "map",
      "final": "primate"
    },
    "medium": {
      "start": "to",
      "final": "tossing"
    },
    "hard": {
      "start": "nest",
      "final": "excretions"
    }
  },
  "2026-08-19": {
    "easy": {
      "start": "i",
      "final": "splitters"
    },
    "medium": {
      "start": "at",
      "final": "pedestal"
    },
    "hard": {
      "start": "antic",
      "final": "placation"
    }
  },
  "2026-08-20": {
    "easy": {
      "start": "us",
      "final": "insure"
    },
    "medium": {
      "start": "dips",
      "final": "despotic"
    },
    "hard": {
      "start": "a",
      "final": "carotenoid"
    }
  },
  "2026-08-21": {
    "easy": {
      "start": "re",
      "final": "sorcery"
    },
    "medium": {
      "start": "dupe",
      "final": "repulsed"
    },
    "hard": {
      "start": "in",
      "final": "reactions"
    }
  },
  "2026-08-22": {
    "easy": {
      "start": "con",
      "final": "anchor"
    },
    "medium": {
      "start": "id",
      "final": "candied"
    },
    "hard": {
      "start": "no",
      "final": "refractions"
    }
  },
  "2026-08-23": {
    "easy": {
      "start": "my",
      "final": "armory"
    },
    "medium": {
      "start": "act",
      "final": "secretary"
    },
    "hard": {
      "start": "en",
      "final": "intending"
    }
  },
  "2026-08-24": {
    "easy": {
      "start": "eve",
      "final": "resolve"
    },
    "medium": {
      "start": "aid",
      "final": "admiral"
    },
    "hard": {
      "start": "us",
      "final": "ruminates"
    }
  },
  "2026-08-25": {
    "easy": {
      "start": "en",
      "final": "matinee"
    },
    "medium": {
      "start": "id",
      "final": "distance"
    },
    "hard": {
      "start": "ta",
      "final": "emancipator"
    }
  },
  "2026-08-26": {
    "easy": {
      "start": "a",
      "final": "restraint"
    },
    "medium": {
      "start": "sequin",
      "final": "equations"
    },
    "hard": {
      "start": "rile",
      "final": "slathering"
    }
  },
  "2026-08-27": {
    "easy": {
      "start": "pie",
      "final": "perspire"
    },
    "medium": {
      "start": "ar",
      "final": "garbage"
    },
    "hard": {
      "start": "indict",
      "final": "periodontics"
    }
  },
  "2026-08-28": {
    "easy": {
      "start": "dip",
      "final": "despair"
    },
    "medium": {
      "start": "rant",
      "final": "decorating"
    },
    "hard": {
      "start": "on",
      "final": "dominance"
    }
  },
  "2026-08-29": {
    "easy": {
      "start": "fa",
      "final": "flaunt"
    },
    "medium": {
      "start": "rutting",
      "final": "cluttering"
    },
    "hard": {
      "start": "i",
      "final": "lacerations"
    }
  },
  "2026-08-30": {
    "easy": {
      "start": "if",
      "final": "filtered"
    },
    "medium": {
      "start": "quire",
      "final": "requiters"
    },
    "hard": {
      "start": "inter",
      "final": "refractions"
    }
  },
  "2026-08-31": {
    "easy": {
      "start": "id",
      "final": "retired"
    },
    "medium": {
      "start": "core",
      "final": "contrive"
    },
    "hard": {
      "start": "grid",
      "final": "badgering"
    }
  },
  "2026-09-01": {
    "easy": {
      "start": "pa",
      "final": "appraise"
    },
    "medium": {
      "start": "lunar",
      "final": "underlay"
    },
    "hard": {
      "start": "nut",
      "final": "caution"
    }
  },
  "2026-09-02": {
    "easy": {
      "start": "sac",
      "final": "desecrate"
    },
    "medium": {
      "start": "tier",
      "final": "carpeting"
    },
    "hard": {
      "start": "go",
      "final": "gorgeous"
    }
  },
  "2026-09-03": {
    "easy": {
      "start": "cap",
      "final": "scrapple"
    },
    "medium": {
      "start": "ba",
      "final": "bayonet"
    },
    "hard": {
      "start": "drag",
      "final": "generated"
    }
  },
  "2026-09-04": {
    "easy": {
      "start": "so",
      "final": "clovers"
    },
    "medium": {
      "start": "nag",
      "final": "restraining"
    },
    "hard": {
      "start": "entice",
      "final": "respecting"
    }
  },
  "2026-09-05": {
    "easy": {
      "start": "er",
      "final": "sapphire"
    },
    "medium": {
      "start": "un",
      "final": "indenture"
    },
    "hard": {
      "start": "dame",
      "final": "exclaimed"
    }
  },
  "2026-09-06": {
    "easy": {
      "start": "fe",
      "final": "deflect"
    },
    "medium": {
      "start": "ad",
      "final": "ironclad"
    },
    "hard": {
      "start": "ace",
      "final": "correlated"
    }
  },
  "2026-09-07": {
    "easy": {
      "start": "red",
      "final": "relaxed"
    },
    "medium": {
      "start": "at",
      "final": "stanchions"
    },
    "hard": {
      "start": "is",
      "final": "despotic"
    }
  },
  "2026-09-08": {
    "easy": {
      "start": "dole",
      "final": "melodic"
    },
    "medium": {
      "start": "gent",
      "final": "pretending"
    },
    "hard": {
      "start": "trounce",
      "final": "countryside"
    }
  },
  "2026-09-09": {
    "easy": {
      "start": "lid",
      "final": "spiraled"
    },
    "medium": {
      "start": "er",
      "final": "remediate"
    },
    "hard": {
      "start": "sine",
      "final": "burnished"
    }
  },
  "2026-09-10": {
    "easy": {
      "start": "den",
      "final": "indexed"
    },
    "medium": {
      "start": "dive",
      "final": "shriveled"
    },
    "hard": {
      "start": "creative",
      "final": "eviscerated"
    }
  },
  "2026-09-11": {
    "easy": {
      "start": "rips",
      "final": "crispier"
    },
    "medium": {
      "start": "ed",
      "final": "excreted"
    },
    "hard": {
      "start": "nag",
      "final": "integrating"
    }
  },
  "2026-09-12": {
    "easy": {
      "start": "sum",
      "final": "supreme"
    },
    "medium": {
      "start": "an",
      "final": "laminator"
    },
    "hard": {
      "start": "ed",
      "final": "repulsed"
    }
  },
  "2026-09-13": {
    "easy": {
      "start": "dig",
      "final": "unsigned"
    },
    "medium": {
      "start": "dues",
      "final": "recaused"
    },
    "hard": {
      "start": "tuna",
      "final": "debutante"
    }
  },
  "2026-09-14": {
    "easy": {
      "start": "so",
      "final": "foolish"
    },
    "medium": {
      "start": "pet",
      "final": "enterprise"
    },
    "hard": {
      "start": "incite",
      "final": "iridescent"
    }
  },
  "2026-09-15": {
    "easy": {
      "start": "amp",
      "final": "campfire"
    },
    "medium": {
      "start": "some",
      "final": "mongrels"
    },
    "hard": {
      "start": "tab",
      "final": "obstinate"
    }
  },
  "2026-09-16": {
    "easy": {
      "start": "lac",
      "final": "actuals"
    },
    "medium": {
      "start": "re",
      "final": "calories"
    },
    "hard": {
      "start": "in",
      "final": "angelic"
    }
  },
  "2026-09-17": {
    "easy": {
      "start": "is",
      "final": "scurried"
    },
    "medium": {
      "start": "cot",
      "final": "coronate"
    },
    "hard": {
      "start": "me",
      "final": "medication"
    }
  },
  "2026-09-18": {
    "easy": {
      "start": "ed",
      "final": "leisured"
    },
    "medium": {
      "start": "dear",
      "final": "replicated"
    },
    "hard": {
      "start": "pics",
      "final": "processing"
    }
  },
  "2026-09-19": {
    "easy": {
      "start": "id",
      "final": "rescind"
    },
    "medium": {
      "start": "doe",
      "final": "undertows"
    },
    "hard": {
      "start": "er",
      "final": "pointier"
    }
  },
  "2026-09-20": {
    "easy": {
      "start": "is",
      "final": "bruised"
    },
    "medium": {
      "start": "cede",
      "final": "recessed"
    },
    "hard": {
      "start": "is",
      "final": "plastering"
    }
  },
  "2026-09-21": {
    "easy": {
      "start": "gin",
      "final": "shirting"
    },
    "medium": {
      "start": "diet",
      "final": "curtsied"
    },
    "hard": {
      "start": "to",
      "final": "rotation"
    }
  },
  "2026-09-22": {
    "easy": {
      "start": "no",
      "final": "solvent"
    },
    "medium": {
      "start": "rate",
      "final": "relevant"
    },
    "hard": {
      "start": "nest",
      "final": "excretions"
    }
  },
  "2026-09-23": {
    "easy": {
      "start": "lad",
      "final": "exalted"
    },
    "medium": {
      "start": "tag",
      "final": "cremating"
    },
    "hard": {
      "start": "antic",
      "final": "placation"
    }
  },
  "2026-09-24": {
    "easy": {
      "start": "net",
      "final": "invert"
    },
    "medium": {
      "start": "ear",
      "final": "visceral"
    },
    "hard": {
      "start": "a",
      "final": "carotenoid"
    }
  }
};
