# -*- coding: utf-8 -*-
"""
generate_schedule.py

Rerun this ANY TIME you add new puzzles (or new solutions) to puzzle_bank.xlsx.

It reads the Excel file and writes TWO files:
  1. ../data/puzzles.js   - the day-by-day schedule the LIVE GAME uses
                            (start/final words only - never includes solutions,
                            so today's and future puzzles are never exposed).
  2. ../data/solutions.js - solutions for PAST days only (yesterday and
                            earlier, based on today's real date when you run
                            this script). Today's and future puzzles' solutions
                            are never written to this file, so re-running the
                            script never leaks an answer early.

HOW TO USE:
1. Update puzzle_bank.xlsx with your new rows / solutions (see the
   "Solution" column below - optional, comma-separated words, e.g.
   "a,at,tan,rant,train,strain,retains,strainer,restraint").
2. Edit START_DATE and NUM_DAYS below if needed.
3. Run:  python3 generate_schedule.py
4. This overwrites ../data/puzzles.js, ../data/solutions.js, and bumps the
   cache-busting version numbers in index.html and solutions.html.
5. Commit + push the updated files to GitHub.

Requires: pip install pandas openpyxl
"""

import pandas as pd
from datetime import date, timedelta
import json
import os
import re
import time

# ---------------- SETTINGS YOU CAN EDIT ----------------
EXCEL_PATH = os.path.join(os.path.dirname(__file__), "puzzle_bank.xlsx")
PUZZLES_OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "puzzles.js")
SOLUTIONS_OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "solutions.js")
HINTS_OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "hints.js")
INDEX_HTML_PATH = os.path.join(os.path.dirname(__file__), "..", "index.html")
SOLUTIONS_HTML_PATH = os.path.join(os.path.dirname(__file__), "..", "solutions.html")

START_DATE = date(2026, 7, 27)  # <-- change this to your real launch date
NUM_DAYS = 10                    # <-- how many days of schedule to generate
# ---------------------------------------------------------

EASY_LEVELS = {"rookie", "beginner"}
MEDIUM_LEVELS = {"novice"}
HARD_LEVELS = {"expert", "wordsmith"}


def parse_solution(raw):
    """Turns 'a,at,tan,rant' into ['a','at','tan','rant']. Returns None if
    the cell is blank/missing, so puzzles without a solution yet are simply
    skipped rather than breaking anything."""
    if raw is None:
        return None
    text = str(raw).strip()
    if not text or text.lower() == "nan":
        return None
    return [w.strip().lower() for w in text.split(",") if w.strip()]


def load_puzzles():
    df = pd.read_excel(EXCEL_PATH, sheet_name="Puzzle Bank")
    df.columns = df.columns.str.strip()
    df = df[df["Level"].isin(EASY_LEVELS | MEDIUM_LEVELS | HARD_LEVELS)]
    df = df.sort_values(by="Assign_Puzzle_Difficulty").reset_index(drop=True)

    has_solution_col = "Solution" in df.columns

    tiers = {"easy": [], "medium": [], "hard": []}
    for _, row in df.iterrows():
        entry = {
            "start": str(row["Starting_Word"]).strip().lower(),
            "final": str(row["Final_Word"]).strip().lower(),
            "solution": parse_solution(row["Solution"]) if has_solution_col else None,
        }
        level = row["Level"]
        if level in EASY_LEVELS:
            tiers["easy"].append(entry)
        elif level in MEDIUM_LEVELS:
            tiers["medium"].append(entry)
        elif level in HARD_LEVELS:
            tiers["hard"].append(entry)
    return tiers


def build_schedule(tiers):
    """Returns the full day-by-day schedule (used to derive both output
    files below), with each day's puzzle entries carrying their solution
    alongside them (solutions.js will later filter this down to past days,
    and puzzles.js will strip solutions out entirely)."""
    schedule = {}
    counters = {"easy": 0, "medium": 0, "hard": 0}
    for i in range(NUM_DAYS):
        the_date = START_DATE + timedelta(days=i)
        key = the_date.isoformat()
        day_entry = {}
        for tier in ("easy", "medium", "hard"):
            pool = tiers[tier]
            if not pool:
                continue
            puzzle = pool[counters[tier] % len(pool)]
            counters[tier] += 1
            day_entry[tier] = puzzle
        schedule[key] = day_entry
    return schedule


def write_puzzles_js(schedule):
    """The live game's data file. Deliberately strips solutions out
    entirely, so nothing in here ever exposes an answer - today's or
    future's - no matter how closely someone inspects it."""
    stripped = {}
    for day_key, day_entry in schedule.items():
        stripped[day_key] = {
            tier: {"start": p["start"], "final": p["final"]}
            for tier, p in day_entry.items()
        }
    with open(PUZZLES_OUTPUT_PATH, "w") as f:
        f.write("// AUTO-GENERATED by scripts/generate_schedule.py - do not hand-edit\n")
        f.write("const PUZZLE_SCHEDULE = ")
        f.write(json.dumps(stripped, indent=2))
        f.write(";\n")
    print(f"Wrote {len(stripped)} days of puzzles to {PUZZLES_OUTPUT_PATH}")


def write_hints_js(schedule):
    """Powers the in-game hint button. Uses the SAME rolling window as
    puzzles.js (today through NUM_DAYS out) rather than a separate/larger
    window, so this never exposes more of the puzzle bank than the live
    game already does."""
    result = {}
    for day_key, day_entry in schedule.items():
        tiers_with_solutions = {
            tier: p for tier, p in day_entry.items() if p.get("solution")
        }
        if tiers_with_solutions:
            result[day_key] = tiers_with_solutions

    with open(HINTS_OUTPUT_PATH, "w") as f:
        f.write("// AUTO-GENERATED by scripts/generate_schedule.py - do not hand-edit\n")
        f.write("// Powers the in-game hint button. Same rolling window as\n")
        f.write("// puzzles.js - not a bigger exposure than the live game already has.\n")
        f.write("const HINTS_SCHEDULE = ")
        f.write(json.dumps(result, indent=2))
        f.write(";\n")
    print(f"Wrote hint data for {len(result)} day(s) to {HINTS_OUTPUT_PATH}")


def write_solutions_js(schedule):
    """Only ever includes YESTERDAY (relative to today's real date, as of
    the last time this script ran) - never today's, future, or older past
    days. Keeps the exposed file as minimal as possible."""
    today = date.today()
    yesterday_key = (today - timedelta(days=1)).isoformat()
    result = {}
    if yesterday_key in schedule:
        day_entry = schedule[yesterday_key]
        tiers_with_solutions = {
            tier: p for tier, p in day_entry.items() if p.get("solution")
        }
        if tiers_with_solutions:
            result[yesterday_key] = tiers_with_solutions

    with open(SOLUTIONS_OUTPUT_PATH, "w") as f:
        f.write("// AUTO-GENERATED by scripts/generate_schedule.py - do not hand-edit\n")
        f.write("// Only ever contains YESTERDAY's puzzles - never today's or\n")
        f.write("// future ones, and nothing older than yesterday either.\n")
        f.write("const SOLUTIONS_SCHEDULE = ")
        f.write(json.dumps(result, indent=2))
        f.write(";\n")
    print(f"Wrote {'1' if result else '0'} day (yesterday) of solutions to {SOLUTIONS_OUTPUT_PATH}")


def bump_cache_version_in(path, script_filename):
    """Force browsers to fetch the freshly generated file instead of a
    cached copy, by rewriting the ?v= number in the given HTML file."""
    if not os.path.exists(path):
        return
    with open(path, "r") as f:
        html = f.read()
    new_version = int(time.time())
    pattern = rf'({re.escape(script_filename)}\?v=)\d+'
    html, count = re.subn(pattern, rf'\g<1>{new_version}', html)
    if count == 0:
        print(f"NOTE: no {script_filename}?v= tag found in {path} to bump "
              f"(fine if that file doesn't reference it).")
        return
    with open(path, "w") as f:
        f.write(html)
    print(f"Bumped cache-busting version for {script_filename} in {path} to {new_version}")


def main():
    tiers = load_puzzles()
    print(f"Loaded puzzles -> easy: {len(tiers['easy'])}, "
          f"medium: {len(tiers['medium'])}, hard: {len(tiers['hard'])}")

    schedule = build_schedule(tiers)
    write_puzzles_js(schedule)
    write_hints_js(schedule)
    write_solutions_js(schedule)

    bump_cache_version_in(INDEX_HTML_PATH, "data/puzzles.js")
    bump_cache_version_in(INDEX_HTML_PATH, "data/hints.js")
    bump_cache_version_in(SOLUTIONS_HTML_PATH, "data/solutions.js")


if __name__ == "__main__":
    main()
