# -*- coding: utf-8 -*-
"""
generate_schedule.py

Rerun this ANY TIME you add new puzzles to puzzle_bank.xlsx.
It reads the Excel file and outputs a fresh data/puzzles.js file
containing a full day-by-day schedule (Easy/Medium/Hard) starting
from START_DATE, for NUM_DAYS days.

HOW TO USE:
1. Update puzzle_bank.xlsx with your new rows (same columns as before).
2. Edit START_DATE and NUM_DAYS below if needed.
3. Run:  python3 generate_schedule.py
4. This overwrites ../data/puzzles.js
5. Commit + push the updated data/puzzles.js to GitHub.

Requires: pip install pandas openpyxl
"""

import pandas as pd
from datetime import date, timedelta
import json
import os

# ---------------- SETTINGS YOU CAN EDIT ----------------
EXCEL_PATH = os.path.join(os.path.dirname(__file__), "puzzle_bank.xlsx")
OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "puzzles.js")

START_DATE = date(2026, 7, 27)  # <-- change this to your real launch date
NUM_DAYS = 60                   # <-- how many days of schedule to generate
# ---------------------------------------------------------

EASY_LEVELS = {"rookie", "beginner"}
MEDIUM_LEVELS = {"novice"}
HARD_LEVELS = {"expert", "wordsmith"}


def load_puzzles():
    df = pd.read_excel(EXCEL_PATH, sheet_name="Puzzle Bank")
    df.columns = df.columns.str.strip()
    df = df[df["Level"].isin(EASY_LEVELS | MEDIUM_LEVELS | HARD_LEVELS)]
    df = df.sort_values(by="Assign_Puzzle_Difficulty").reset_index(drop=True)

    tiers = {"easy": [], "medium": [], "hard": []}
    for _, row in df.iterrows():
        entry = {
            "start": str(row["Starting_Word"]).strip().lower(),
            "final": str(row["Final_Word"]).strip().lower(),
        }
        level = row["Level"]
        if level in EASY_LEVELS:
            tiers["easy"].append(entry)
        elif level in MEDIUM_LEVELS:
            tiers["medium"].append(entry)
        elif level in HARD_LEVELS:
            tiers["hard"].append(entry)
    return tiers


def build_schedule(tiers):
    schedule = {}
    counters = {"easy": 0, "medium": 0, "hard": 0}
    for i in range(NUM_DAYS):
        the_date = START_DATE + timedelta(days=i)
        key = the_date.isoformat()
        day_entry = {}
        for tier in ("easy", "medium", "hard"):
            pool = tiers[tier]
            if not pool:
                continue
            puzzle = pool[counters[tier] % len(pool)]
            counters[tier] += 1
            day_entry[tier] = puzzle
        schedule[key] = day_entry
    return schedule


def main():
    tiers = load_puzzles()
    print(f"Loaded puzzles -> easy: {len(tiers['easy'])}, "
          f"medium: {len(tiers['medium'])}, hard: {len(tiers['hard'])}")

    schedule = build_schedule(tiers)

    with open(OUTPUT_PATH, "w") as f:
        f.write("// AUTO-GENERATED by scripts/generate_schedule.py - do not hand-edit\n")
        f.write("const PUZZLE_SCHEDULE = ")
        f.write(json.dumps(schedule, indent=2))
        f.write(";\n")

    print(f"Wrote schedule for {NUM_DAYS} days to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
